version: "3.8"

services:
  # Backend server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: bookmarkeddit-server
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    networks:
      - bookmarkeddit-network
    volumes:
      - server-logs:/usr/src/app/logs

  # Frontend app
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: bookmarkeddit-app
    restart: unless-stopped
    env_file:
      - ./app/.env
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - bookmarkeddit-network

networks:
  bookmarkeddit-network:
    driver: bridge

volumes:
  server-logs:
